[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
not_a_bet = "6Suc2n5Yf9ZwXWJdq4JzxbMNP4BJuEQ9YhTn7Btjgde7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dr222/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
